In [18]:
import datascience as ds
import numpy as np
import pandas as pd
import string

# Creating a Table from scratch

In order to create a Table object, you need two things: a list of data columns and a set of labels for those columns.


In [151]:
nfeats = 10
data = list(np.random.randn(nfeats, 100))
labels = [string.ascii_lowercase[i] for i in range(nfeats)]
table = ds.Table(data, labels=labels)

You can also supply a dictionary where keys are labels and values are the column data

In [24]:
data_dict = {i: dat for i, dat in zip(labels, data)}
table = ds.Table(data_dict)

If you want to create a table by passing rows instead of columns, use the `from_rows` method

In [143]:
data_rows = list(np.random.randn(100, nfeats))
table = ds.Table.from_rows(data_rows, column_labels=labels)

# Viewing Data

In a jupyter notebook, simply run a cell with a table in it, and it will display in nice HTML. However, it will cut off rows that are too long to be displayed

In [33]:
table

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

In [34]:
# Printing does the same, but with text output
print(table)

a         | b          | c          | d          | e         | f          | g         | h         | i         | j
0.406769  | 1.55196    | -0.0931095 | -0.529943  | 1.78406   | 1.68528    | 1.84819   | -1.9656   | -0.596316 | 0.0727995
1.94665   | -0.879404  | -0.313696  | -1.29964   | 0.473706  | -0.41833   | 0.980287  | 0.726492  | 1.14417   | 2.3054
-0.229707 | 0.187612   | -2.22901   | -0.43925   | -0.752164 | -2.24453   | -0.743171 | 0.0202779 | -0.443438 | -0.431859
0.797457  | -0.871438  | 1.51265    | 0.566548   | -0.130461 | -1.24734   | -0.151947 | 1.21087   | 1.90886   | -0.362355
0.140173  | 0.295714   | 1.3674     | 1.96185    | 0.0973633 | -0.0300836 | 0.960287  | 1.04089   | 0.153897  | -1.4037
1.19691   | 0.115993   | 0.327456   | -0.0467045 | 0.091842  | 0.980452   | -1.69135  | -0.57797  | -0.124096 | -0.245333
0.506299  | -0.0383577 | 0.141138   | 1.03598    | 0.295396  | -0.48896   | -0.902124 | -0.565999 | 1.87611   | -0.0758977
-0.652332 | -0.1099    | -1.23547   

In [44]:
# You can return a table as text
print('TEXT:\n', table.as_text()[:1000])

# Or as html
print('\n\nHTML:\n', table.as_html()[:1000])

TEXT:
 a           | b            | c          | d          | e           | f          | g          | h          | i          | j
0.406769    | 1.55196      | -0.0931095 | -0.529943  | 1.78406     | 1.68528    | 1.84819    | -1.9656    | -0.596316  | 0.0727995
1.94665     | -0.879404    | -0.313696  | -1.29964   | 0.473706    | -0.41833   | 0.980287   | 0.726492   | 1.14417    | 2.3054
-0.229707   | 0.187612     | -2.22901   | -0.43925   | -0.752164   | -2.24453   | -0.743171  | 0.0202779  | -0.443438  | -0.431859
0.797457    | -0.871438    | 1.51265    | 0.566548   | -0.130461   | -1.24734   | -0.151947  | 1.21087    | 1.90886    | -0.362355
0.140173    | 0.295714     | 1.3674     | 1.96185    | 0.0973633   | -0.0300836 | 0.960287   | 1.04089    | 0.153897   | -1.4037
1.19691     | 0.115993     | 0.327456   | -0.0467045 | 0.091842    | 0.980452   | -1.69135   | -0.57797   | -0.124096  | -0.245333
0.506299    | -0.0383577   | 0.141138   | 1.03598    | 0.295396    | -0.48896   | -0.9021

You can also just access the column labels

In [49]:
cols = table.column_labels
print(cols)

('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j')


Transposing your data will not change your column labels. Instead, it will transpose the data __within__ each column.

In [52]:
table.T

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

You can also sort a table by the values in some column.

In [56]:
table.sort('b')

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

# Selecting data
The simplest way of selecting data is by pulling out individual columns. This can be done by putting the column name in brackets (similar to how dictionaries work). Note that you must supply a single column name.

In [64]:
print(table['a'][:5])

[ 0.40676911  1.946647   -0.22970666  0.79745695  0.14017344]


Alternatively, one can select a subset of columns for viewing with the `.select` method. This lets you give multiple column labels:

In [67]:
table.select(['a', 'b'])

<Table(2 rows): | a | b |>

Finally, it is also possible to take specific rows from a table with the `.take` method. Note that this uses a list of row indices.

In [71]:
ix_rows = range(10, 20)
table.take(ix_rows)

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

Finally, if you want to forget about the column labels and just treat it as a numpy array, you can use the `.columns` attribute. This will return a list of your column values, which is easily converted into a numpy array (but note that this will also transpose the data)

In [112]:
table_array = table.columns
table_array = np.array(table_array)
print(table_array[:5, :5])
print(type(table_array))

[[ 0.40676911  1.946647   -0.22970666  0.79745695  0.14017344]
 [ 1.5519589  -0.87940394  0.1876115  -0.87143836  0.29571392]
 [-0.09310951 -0.31369648 -2.22901218  1.5126497   1.36739613]
 [-0.52994258 -1.29964241 -0.43925049  0.56654829  1.96185154]
 [ 1.78405945  0.47370562 -0.75216434 -0.1304611   0.09736333]]
<class 'numpy.ndarray'>


## Boolean indexing

You can't use boolean operators directly with a Table, but it is quite easy to accomplish the same thing by selecting a subset of the data to create boolean masks, then by using the `.where` method.

In [113]:
table > 1

TypeError: unorderable types: Table() > int()

In [115]:
# We'll convert the matrix to an array
msk = np.array(table.columns) > 1
msk[:5, :5]

array([[False,  True, False, False, False],
       [ True, False, False, False, False],
       [False, False, False,  True,  True],
       [False, False, False, False,  True],
       [ True, False, False, False, False]], dtype=bool)

Now we can use the `.where` method, which takes an array with the length == the number of rows in our Table, and returns the rows where the array is == "value" (which defaults to the value `True`)

In [118]:
table.where(msk[0])

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

In [129]:
msk_letter = msk.copy().astype(str)
msk_letter[msk] = 'a'
msk_letter[~msk] = 'b'
print(msk_letter[:5, :5])

[['b' 'a' 'b' 'b' 'b']
 ['a' 'b' 'b' 'b' 'b']
 ['b' 'b' 'b' 'a' 'a']
 ['b' 'b' 'b' 'b' 'a']
 ['a' 'b' 'b' 'b' 'b']]


In [128]:
table.where(msk_letter[0], 'b')

<Table(10 rows): | a | b | c | d | e | f | g | h | i | j |>

# Adding new data
It is possible to add a new column directly to our Table object. This is done by passing values that have the same number of rows, along with a column name

In [152]:
table['custom_col'] = table['a'] + 100
table['custom_col']

array([ 100.71203456,  101.02437246,  101.42301705,  100.07765536,
        100.7550972 ,   98.9727203 ,   98.66095711,  100.13710886,
        100.33388808,  100.4211912 ,   98.5679226 ,  100.56498883,
        100.07779845,   98.71167394,  101.10158842,  100.71620285,
         99.17222072,   98.38321062,  100.550448  ,   99.2507432 ,
        100.62281287,  101.93299852,  100.38797408,   99.34322741,
         98.53224889,  100.01835533,   99.57473656,   98.23392258,
        101.6291059 ,   99.11885732,   98.77564795,  100.85666664,
        100.18165585,   99.20889181,  100.11799917,  100.70664996,
        101.01061018,   99.12809131,  100.47232331,  101.88621109,
         98.75524666,  100.61839017,  100.13342417,  100.49287363,
         99.08813087,  101.15083087,   99.57929517,   99.74852665,
         99.15111061,  101.49228669,   99.49050557,   99.60957761,
        101.26757898,   99.79825213,  101.95194058,  101.36793204,
        100.82254048,  100.7016186 ,  101.21617388,   99.79459

In [156]:
table['not_a'] = table['a'] < 0
table

<Table(12 rows): | a | b | c | d | e | f | g | h | i | j | custom_col | not_a |>

# Operations

Tables aren't meant to be operated on directly. Instead, you should operate on their data, e.g.:

In [159]:
table + 2

TypeError: unsupported operand type(s) for +: 'Table' and 'int'

In [161]:
table['a+2'] = table['a'] + 2

It is possible to do some simple statistics on the table object as well.

In [ ]:
np.mean(table)

Or you can apply an arbitrary function to a specific column:

In [180]:
def turn_into_chris(i):
    return 'chris'

# *each row* of the column will be passed to our function
table['a_chris'] = table.apply(turn_into_chris, 'a')
table['a_chris'][:5]

array(['chris', 'chris', 'chris', 'chris', 'chris'], 
      dtype='<U5')

# Merging / joining / etc

# Grouping

# Plotting
There are a few plotting methods associated with a Table object. These can do some quick visualizations of your data.

In [182]:
table.plot('c')

ValueError: could not convert string to float: 'chris'

# Pivot tables

# IO